# Generated by Django 4.1.7 on 2023-02-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Addition'), (2, 'Subtraction'), (3, 'Multiplication'), (4, 'Division'), (5, 'Square root'), (6, 'Random string')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
